### PR TITLE
Parallelize the travis build

### PR DESCRIPTION
**Pull request by winhamwr**
Faster is better!

### CODE REVIEW

**Comment by winhamwr** [comment]
@kylegibson Do you have any idea why we get intermittent socket errors downloading things with pip when doing builds?

I ran the build twice and a different environment failed each time with a traceback like this:

```
Building new environment
Traceback (most recent call last):
  File "/tmp/terrarium_bootstrap-b9O496.py", line 2645, in <module>
    main()
  File "/tmp/terrarium_bootstrap-b9O496.py", line 983, in main
    after_install(options, home_dir)
  File "/tmp/terrarium_bootstrap-b9O496.py", line 1973, in after_install
    requirementSet = c.run(options, args)
  File "/tmp/test_terrarium_target-yW7IVq/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/tmp/test_terrarium_target-yW7IVq/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 1033, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/tmp/test_terrarium_target-yW7IVq/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 1161, in unpack_url
    retval = unpack_http_url(link, location, self.download_cache, self.download_dir)
  File "/tmp/test_terrarium_target-yW7IVq/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/download.py", line 554, in unpack_http_url
    download_hash = _download_url(resp, link, temp_location)
  File "/tmp/test_terrarium_target-yW7IVq/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/download.py", line 458, in _download_url
    chunk = resp.read(4096)
  File "/opt/python/2.7.9/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/opt/python/2.7.9/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/opt/python/2.7.9/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/opt/python/2.7.9/lib/python2.7/ssl.py", line 714, in recv
    return self.read(buflen)
  File "/opt/python/2.7.9/lib/python2.7/ssl.py", line 608, in read
    v = self._sslobj.read(len or 1024)
socket.error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/travis/build/PolicyStat/terrarium/.tox/py27-venv-1.9.1/bin/terrarium", line 9, in <module>
    load_entry_point('terrarium==1.0.0rc6', 'console_scripts', 'terrarium')()
  File "/home/travis/build/PolicyStat/terrarium/.tox/py27-venv-1.9.1/lib/python2.7/site-packages/terrarium/terrarium.py", line 956, in main
    r = terrarium.install()
  File "/home/travis/build/PolicyStat/terrarium/.tox/py27-venv-1.9.1/lib/python2.7/site-packages/terrarium/terrarium.py", line 216, in install
    new_target
  File "/home/travis/build/PolicyStat/terrarium/.tox/py27-venv-1.9.1/lib/python2.7/site-packages/virtualenv.py", line 1057, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/travis/build/P...-1.9.1/bin/python2.7 /tmp/terrarium_bootstrap-b9O496.py --prompt=(test_terrarium_target-yW7IVq) /tmp/test_terrarium_target-yW7IVq failed with error code 1
```

**Comment by kylegibson** [comment]
I don't think I've ever seen that error before

**Comment by winhamwr** [comment]
It also happened in [this build](https://travis-ci.org/PolicyStat/terrarium/builds/46935166).

**Comment by kylegibson** [comment]
Looks good

**Pull request merged**
